yum_packages:
  - epel-release

ec2_region: eu-west-1
ec2_vpc_id: vpc-XXX
ec2_amis:
  eu_west_1_centos_7_2002_01: ami-0b850cf02cc00fdc8
ec2_subnets:
  first: subnet-XXX
  second: subnet-YYY
  third: subnet-ZZZ

ec2_security_group_prefix:
ec2_security_groups:
  - name: internal
    desc: Default
    rules:
      - proto: all
        cidr_ip: 10.0.0.0/8

  - name: public_http
    desc: Public HTTP Services
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0

ec2_key_name: deployer
ec2_default_tags: {Project: test}
# ec2_instance_name_prefix: test-
ec2_instances:
  - {name: app-01, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.first }}', security_groups: [internal], tags: {Group: app}}
  - {name: app-02, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.first }}', security_groups: [internal], tags: {Group: app}}
  - {name: app-03, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.second }}', security_groups: [internal], tags: {Group: app}}
  - {name: app-04, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.second }}', security_groups: [internal], tags: {Group: app}}
  - {name: app-05, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.third }}', security_groups: [internal], tags: {Group: app}}
  - {name: web-01, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.first }}', security_groups: [internal, public_http], tags: {Group: web}, assign_public_ip: yes}
  - {name: web-02, ami: '{{ ec2_amis.eu_west_1_centos_7_2002_01 }}', subnet: '{{ ec2_subnets.second }}', security_groups: [internal, public_http], tags: {Group: web}, assign_public_ip: yes}
